### PR TITLE
Fix packets close to max packet size

### PR DESCRIPTION
**Pull request by jorgenpt**
Fixes GH-27

### CODE REVIEW

**Comment by jorgenpt** [comment]
@gafferongames, let me know if you've got any feedback on the fix or the test.

**Review by gafferongames — CHANGES_REQUESTED** [review]
This looks great. The only change I would request is that since anybody can send UDP packets to an application, it is better to turn the reliable_printf on too large packet received into a RELIABLE_LOG_LEVEL_DEBUG

Otherwise, people using this get scared when they see (some other application) spamming them with too large packets on their port, and they think something is wrong.

thanks :)

**Comment by jorgenpt** [comment]
@gafferongames What about the log statements in `reliable_read_packet_header`? Should those be swapped to DEBUG as well, since for random internet packets that are the right size they're likely to have an invalid header. I figure the error log on the second packet size validation is fine to leave as an error since it requires the packet header to be valid :)

**Comment by gafferongames** [comment]
Generally, when logging on receive packet, for logs that can be induced by being unlucky enough to receive random packets from some other application -- I prefer debug logos there too, thanks

**Comment by gafferongames** [comment]
Yes, those should be swapped as well. Thanks

**Comment by jorgenpt** [comment]
Okay, should be good now (I also rebased it and fixed an issue with the merge to the other recently merged changes that made the tests fail).

**Pull request merged**
